title: Does this work
description: Let's see
theme: just-the-docs

url: https://NavSi08.github.io/doesthiswork

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
